# These are supported funding model platforms

buy_me_a_coffee & thanks_dev: 
custom: [ My ENS domain: "https://app.ens.domains/arewa.eth", My Basename: "https://www.base.org/name/arewa", My domain addy: "https://ud.me/zahrah.nft", My near wallet: "https://nearblocks.io/address/zahrah.near", my ton wallet: "https://tonviewer.com/realworldasset.ton"]
